<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title>
			
		</title>
		<link rel="stylesheet" type="text/css" href="/css/base.css" />
		<link rel="stylesheet" type="text/css" href="/css/skeleton.css" />
		<link rel="stylesheet" type="text/css" href="/css/layout.css" />
		<link rel="stylesheet" type="text/css" href="/css/print.css" />
		<link rel="shortcut icon" href="/favicon.ico" />
		<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
		<script type="text/javascript" src="/js/general.js"></script>
	</head>
	<body>
		<h1 class="no-display"></h1>
		<div id="wrapper" class="container">
			
			<div id="content">
				<?php echo $this->layout()->content; ?>
			</div> <!-- end #content -->

		</div> <!-- end #wrapper -->
	</body>
</html>