<?php if ($this->pageCount > 1): ?>
<div class="pagination-control">
	<div class="pagination-prev-first padded">
		<!-- First page link -->
		<?php if (isset($this->previous)): ?>
		  <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'users', 'page' => $this->first), 'default'); ?>">
		    &laquo; First</a> |
		<?php else: ?>
		  <span class="disabled">&laquo; First |</span>
		<?php endif; ?>

		<!-- Previous page link -->
		<?php if (isset($this->previous)): ?>
		  <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'users', 'page' => $this->previous), 'default'); ?>">
		    &larr; Previous</a>
		<?php else: ?>
		  <span class="disabled">&larr; Previous </span>
		<?php endif; ?>
	</div>
	
	<div class="pagination-summary padded">
		Showing <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
		 of <?php echo $this->totalItemCount; ?> Items
	</div> 


	
	<div class="pagination-next-last padded">
		<!-- Next page link -->
		<?php if (isset($this->next)): ?>
		  <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'users', 'page' => $this->next), 'default'); ?>">
		    Next &rarr;</a> |
		<?php else: ?>
		  <span class="disabled">Next &rarr; |</span>
		<?php endif; ?>

		<!-- Last page link -->
		<?php if (isset($this->next)): ?>
		  <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'users', 'page' => $this->last), 'default'); ?>">
		    Last &raquo;</a>
		<?php else: ?>
		  <span class="disabled">Last &raquo;</span>
		<?php endif; ?>
	</div> 


</div>
<?php endif; ?>