<div id="admin-export" class="sixteen columns">
	<h2>Export Site Data</h2>
</div> <!-- end #admin-export -->
<div id="dashboard">
	<div class="eight columns">
		<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'export-data', 'data' => 'users'), 'default', true) ?>" class="button">
			Export Users
		</a>
	</div> 
	
	<div class="eight columns">
		<a href="<?php echo $this->url(array('controller'=>'admin', 'action' => 'export-data', 'data' => 'reservations'), 'default', true) ?>" class="button">
			Export Reservations
		</a>
	</div>
	
	<div class="eight columns">
		<a href="<?php echo $this->url(array('controller'=>'admin', 'action' => 'export-data', 'data' => 'transactions'), 'default', true) ?>" class="button">
			Export Transactions
		</a>
	</div>
</div> <!-- end #dashboard -->